-- ════════════════════════════════════════════════════════════════════
-- Migration 0010 — Seed del repositorio de UTMs (desde Excel del equipo)
-- ════════════════════════════════════════════════════════════════════
-- Carga los UTMs ya creados (archivo links_utm_ordenados_actualizado.xlsx).
-- Idempotente: solo inserta los que todavía no estén (match por url).
-- Agrega la columna `organization` (Peterson o Control Union) si falta.
--
-- Cómo correr: Supabase Dashboard → SQL Editor → pegar → Run
-- ════════════════════════════════════════════════════════════════════

alter table public.utm_links add column if not exists organization text;

insert into public.utm_links
  (label, url, source, medium, business_unit, organization, country, service, campaign_name, utm_campaign)
select v.label, v.url, v.source, v.medium, v.business_unit, v.organization, v.country, v.service, v.campaign_name, v.utm_campaign
from (values
  ('Webinar Cannabis - BBDD Ottawa Attendee','https://app.livestorm.co/controlunion/the-global-cannabis-series?s=6423a88f-dad0-46cc-b6ff-8b29a72f3834&utm_source=contenido&utm_medium=email_mkt&utm_campaign=cu_certificaciones_canada_certificaciones_marcomms_cannabis_ottawa_attendee','contenido','email_mkt','CU Certificaciones','Control Union','Canada','Certificaciones','Webinar Cannabis - BBDD Ottawa Attendee','cu_certificaciones_canada_certificaciones_marcomms_cannabis_ottawa_attendee'),
  ('Webinar Cannabis - BBDD Cannabis Webinar Report','https://app.livestorm.co/controlunion/the-global-cannabis-series?s=6423a88f-dad0-46cc-b6ff-8b29a72f3834&utm_source=contenido&utm_medium=email_mkt&utm_campaign=cu_certificaciones_canada_certificaciones_marcomms_cannabis_cannabis_webinar_report','contenido','email_mkt','CU Certificaciones','Control Union','Canada','Certificaciones','Webinar Cannabis - BBDD Cannabis Webinar Report','cu_certificaciones_canada_certificaciones_marcomms_cannabis_cannabis_webinar_report'),
  ('Webinar Cannabis - BBDD Certification Leads','https://app.livestorm.co/controlunion/the-global-cannabis-series?s=6423a88f-dad0-46cc-b6ff-8b29a72f3834&utm_source=contenido&utm_medium=email_mkt&utm_campaign=cu_certificaciones_canada_certificaciones_marcomms_cannabis_certification_leads','contenido','email_mkt','CU Certificaciones','Control Union','Canada','Certificaciones','Webinar Cannabis - BBDD Certification Leads','cu_certificaciones_canada_certificaciones_marcomms_cannabis_certification_leads'),
  ('Webinar Cannabis - BBDD CUMCS Clients and Potential Clients','https://app.livestorm.co/controlunion/the-global-cannabis-series?s=6423a88f-dad0-46cc-b6ff-8b29a72f3834&utm_source=contenido&utm_medium=email_mkt&utm_campaign=cu_certificaciones_canada_certificaciones_marcomms_cannabis_cumcs','contenido','email_mkt','CU Certificaciones','Control Union','Canada','Certificaciones','Webinar Cannabis - BBDD CUMCS Clients and Potential Clients','cu_certificaciones_canada_certificaciones_marcomms_cannabis_cumcs'),
  ('Webinar Cannabis - BBDD Apollo','https://app.livestorm.co/controlunion/the-global-cannabis-series?s=6423a88f-dad0-46cc-b6ff-8b29a72f3834&utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_canada_certificaciones_marcomms_cannabis_apollo','contenido','email_mkt','CU Certificaciones','Control Union','Canada','Certificaciones','Webinar Cannabis - BBDD Apollo','control_union_canada_certificaciones_marcomms_cannabis_apollo'),
  ('Webinar Cannabis - LinkedIn','https://app.livestorm.co/controlunion/the-global-cannabis-series?s=6423a88f-dad0-46cc-b6ff-8b29a72f3834&utm_source=contenido&utm_medium=linkedin&utm_campaign=control_union_canada_certificaciones_marcomms_webinar_cannabis','contenido','linkedin','CU Certificaciones','Control Union','Canada','Certificaciones','Webinar Cannabis - LinkedIn','control_union_canada_certificaciones_marcomms_webinar_cannabis'),
  ('Webinar Cannabis - Landing Page','https://app.livestorm.co/controlunion/the-global-cannabis-series?s=6423a88f-dad0-46cc-b6ff-8b29a72f3834&utm_source=contenido&utm_medium=google&utm_campaign=control_union_canada_certificaciones_marcomms_webinar_cannabis','contenido','google','CU Certificaciones','Control Union','Canada','Certificaciones','Webinar Cannabis - Landing Page','control_union_canada_certificaciones_marcomms_webinar_cannabis'),
  ('ISO 27001 - Formulario CEOs y Legales','https://form.typeform.com/to/sKfkBtrN?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_brasil_certificaciones_marcomms_iso_27001_form&typeform-source=statics.teams.cdn.office.net','contenido','email_mkt','CU Certificaciones','Control Union','Brasil','Certificaciones','ISO 27001 - Formulario CEOs y Legales','control_union_brasil_certificaciones_marcomms_iso_27001_form'),
  ('ISO 27001 - ITs','https://form.typeform.com/to/ZbcN4zca?typeform-source=statics.teams.cdn.office.net&utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_brasil_certificaciones_marcomms_iso_27001_ceos','contenido','email_mkt','CU Certificaciones','Control Union','Brasil','Certificaciones','ISO 27001 - ITs','control_union_brasil_certificaciones_marcomms_iso_27001_ceos'),
  ('Webinar AquaUpdate 2026 - Landing Page','https://app.livestorm.co/controlunion/aquaupdate-2026-certificate-o-quedate-atras?utm_source=contenido&utm_medium=google&utm_campaign=marcomms_mexico_certificaciones_marcomms_aqua','contenido','google','CU Certificaciones','Control Union','Mexico','Certificaciones','Webinar AquaUpdate 2026 - Landing Page','marcomms_mexico_certificaciones_marcomms_aqua'),
  ('Webinar AquaUpdate 2026 - LKN','https://app.livestorm.co/controlunion/aquaupdate-2026-certificate-o-quedate-atras?utm_source=contenido&utm_medium=google&utm_campaign=marcomms_mexico_certificaciones_marcomms_aqua','contenido','google','CU Certificaciones','Control Union','Mexico','Certificaciones','Webinar AquaUpdate 2026 - LKN','marcomms_mexico_certificaciones_marcomms_aqua'),
  ('Webinar AquaUpdate 2026 - Landing Page','https://app.livestorm.co/controlunion/aquaupdate-2026-certificate-o-quedate-atras/live?s=080a5d49-8deb-4494-93df-6d328d63a74f&utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_mexico_certificaciones_marcomms_grabacion_webinar_aqua#/','contenido','email_mkt','CU Certificaciones','Control Union','Mexico','Certificaciones','Webinar AquaUpdate 2026 - Landing Page','control_union_mexico_certificaciones_marcomms_grabacion_webinar_aqua'),
  ('Webinar AquaUpdate 2026 - LKN','https://app.livestorm.co/controlunion/aquaupdate-2026-certificate-o-quedate-atras/live?s=080a5d49-8deb-4494-93df-6d328d63a74f&utm_source=contenido&utm_medium=linkedin&utm_campaign=control_union_mexico_certificaciones_marcomms_grabacion_webinar_aqua#/','contenido','linkedin','CU Certificaciones','Control Union','Mexico','Certificaciones','Webinar AquaUpdate 2026 - LKN','control_union_mexico_certificaciones_marcomms_grabacion_webinar_aqua'),
  ('Typeform CEOS y Legales','https://brasil.controlunion.com/programas-de-certificacao/iso-27001/?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_brasil_certificaciones_marcomms_formulario_iso_27001_ceos_y_legales','contenido','email_mkt','CU Certificaciones','Control Union','Brasil','Certificaciones','Typeform CEOS y Legales','control_union_brasil_certificaciones_marcomms_formulario_iso_27001_ceos_y_legales'),
  ('Typeform IT','https://brasil.controlunion.com/programas-de-certificacao/iso-27001/?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_brasil_certificaciones_marcomms_formulario_iso_27001_it','contenido','email_mkt','CU Certificaciones','Control Union','Brasil','Certificaciones','Typeform IT','control_union_brasil_certificaciones_marcomms_formulario_iso_27001_it'),
  ('ISO 27001 LP','https://brasil.controlunion.com/programas-de-certificacao/iso-27001/?utm_source=contenido&utm_medium=email_mkt&utm_campaign=marcomms_brasil_certificaciones_marcomms_iso27001','contenido','email_mkt','CU Certificaciones','Control Union','Brasil','Certificaciones','ISO 27001 LP','marcomms_brasil_certificaciones_marcomms_iso27001'),
  ('ISO 14064','https://app.livestorm.co/controlunion/iso-14064-en-accion-validacion-y-verificacion-de-huella-de-carbono?utm_source=contenido&utm_medium=linkedin&utm_campaign=control_union_mexico_certificaciones_marcomms_iso_14064_en_accion','contenido','linkedin','Control Union','Control Union','Mexico','Certificaciones','ISO 14064','control_union_mexico_certificaciones_marcomms_iso_14064_en_accion'),
  ('Congreso palma de aceite','https://fedepalma.org/congreso-palmero/#expositores?utm_source=contenido&utm_medium=linkedin&utm_campaign=marcomms_colombia_certificaciones_marcomms_congreso_nacional_de_cultivadores_de_palma_de_aceite','contenido','linkedin','Control Union','Control Union','Colombia','Certificaciones','Congreso palma de aceite','marcomms_colombia_certificaciones_marcomms_congreso_nacional_de_cultivadores_de_palma_de_aceite'),
  ('Impacto en la industria textil','https://forms.office.com/Pages/ResponsePage.aspx?id=qvPCT8Qxy023GcbBY5Pp07kFvV3fJPBBlGkv8VYGUppUMk5QOTJCWFZWV01MTDNKMVNSQkJRS1ZYUC4u&utm_source=contenido&utm_medium=linkedin&utm_campaign=marcomms_colombia_certificaciones_marcomms_normas_textiles_alcance_e_impacto_en_la_industria_textil','contenido','linkedin','Control Union','Control Union','Colombia','Certificaciones','Impacto en la industria textil','marcomms_colombia_certificaciones_marcomms_normas_textiles_alcance_e_impacto_en_la_industria_textil'),
  ('Mexico energy forum 2026','https://mexicobusiness.events/energy/2026/06?utm_source=Linkedin&utm_medium=Social%20Media&utm_campaign=Mexico%20Energy%20Froum%202026','Linkedin','Social Media','Control Union','Control Union','','','Mexico energy forum 2026','Mexico Energy Froum 2026'),
  ('Green choice - BBDD Contactos principales','https://mexico.controlunion.com/programa-de-certificacion/green-choice-certificacion-turismo-sostenible/?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_mexico_certificaciones_marcomms_green_choice_contactos_principales','contenido','email_mkt','CU Certificaciones','Control Union','Mexico','Certificaciones','Green choice - BBDD Contactos principales','control_union_mexico_certificaciones_marcomms_green_choice_contactos_principales'),
  ('Green choice - BBDD Hoteles','https://mexico.controlunion.com/programa-de-certificacion/green-choice-certificacion-turismo-sostenible/?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_mexico_certificaciones_marcomms_green_choice_hoteles','contenido','email_mkt','CU Certificaciones','Control Union','Mexico','Certificaciones','Green choice - BBDD Hoteles','control_union_mexico_certificaciones_marcomms_green_choice_hoteles'),
  ('Green choice - BBDD Extra Contactos','https://mexico.controlunion.com/programa-de-certificacion/green-choice-certificacion-turismo-sostenible/?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_mexico_certificaciones_marcomms_green_choice_extra_contacts','contenido','email_mkt','CU Certificaciones','Control Union','Mexico','Certificaciones','Green choice - BBDD Extra Contactos','control_union_mexico_certificaciones_marcomms_green_choice_extra_contacts'),
  ('ISO 27001 USA - Juan y Kevin Invitados','https://app.livestorm.co/controlunion/iso-27001-the-standard-behind-trusted-information-security?s=78ee61f0-c4aa-4206-bed7-3b2dfae176af&utm_source=contenido&utm_medium=meta&utm_campaign=control_union_usa_certificaciones_marcomms_iso_27001_usa_juan_y_kevin_inv','contenido','meta','CU Certificaciones','Control Union','USA','Certificaciones','ISO 27001 USA - Juan y Kevin Invitados','control_union_usa_certificaciones_marcomms_iso_27001_usa_juan_y_kevin_inv'),
  ('ISO 27001 ESP - Juan y Kevin','https://app.livestorm.co/controlunion/cciberseguridad-en-riesgo-lo-que-no-estas-viendo-y-como-iso-27001-puede-ayudarte?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_espana_certificaciones_marcomms_iso27001_espana','contenido','email_mkt','CU Certificaciones','Control Union','España','Certificaciones','ISO 27001 ESP - Juan y Kevin','control_union_espana_certificaciones_marcomms_iso27001_espana'),
  ('ISO 27001 ESP - Juan y Kevin Invitados','https://app.livestorm.co/controlunion/cciberseguridad-en-riesgo-lo-que-no-estas-viendo-y-como-iso-27001-puede-ayudarte?utm_source=contenido&utm_medium=linkedin&utm_campaign=control_union_espana_certificaciones_marcomms_iso27001_espana_kevin_y_juan','contenido','linkedin','CU Certificaciones','Control Union','España','Certificaciones','ISO 27001 ESP - Juan y Kevin Invitados','control_union_espana_certificaciones_marcomms_iso27001_espana_kevin_y_juan'),
  ('Introducción a SMETA 7.0','https://us02web.zoom.us/meeting/register/4PhI6-qETlmrS0hF-Hwr7Q#/registration?utm_source=contenido&utm_medium=linkedin&utm_campaign=control_union_mexico_certificaciones_marcomms_introduccion_a_smeta_70_alcance_requisitos_y_tendencias_en_auditorias_de_sostenibilidad','contenido','linkedin','Control Union','Control Union','Mexico','Certificaciones','Introducción a SMETA 7.0','control_union_mexico_certificaciones_marcomms_introduccion_a_smeta_70_alcance_requisitos_y_tendencias_en_auditorias_de_sostenibilidad'),
  ('ventajas de auditarse en SMETA','https://events.teams.microsoft.com/event/2eab3642-6eeb-4400-9604-a8c87c21316b@4fc2f3aa-31c4-4dcb-b719-c6c16393e9d3?utm_source=contenido&utm_medium=linkedin&utm_campaign=control_union_peru_certificaciones_marcomms_ventajas_de_auditarse_en_smeta','contenido','linkedin','Control Union','Control Union','Peru','Certificaciones','ventajas de auditarse en SMETA','control_union_peru_certificaciones_marcomms_ventajas_de_auditarse_en_smeta'),
  ('Follow Up - ISO 27001 - Guia Practica','https://hubs.ly/Q04lzbNc0?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_espana_certificaciones_marcomms_iso_27001_guia_practica','contenido','email_mkt','CU Certificaciones','Control Union','España','Certificaciones','Follow Up - ISO 27001 - Guia Practica','control_union_espana_certificaciones_marcomms_iso_27001_guia_practica'),
  ('Follow Up - ISO 27001 - Click Checklist','https://hubs.ly/Q04lzfR70?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_espana_certificaciones_marcomms_iso_27001_client_checklist','contenido','email_mkt','CU Certificaciones','Control Union','España','Certificaciones','Follow Up - ISO 27001 - Click Checklist','control_union_espana_certificaciones_marcomms_iso_27001_client_checklist'),
  ('Follow Up - ISO 27001 - Commercial PPT','https://hubs.ly/Q04lzgrZ0?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_espana_certificaciones_marcomms_iso_27001_commercial_ppt','contenido','email_mkt','CU Certificaciones','Control Union','España','Certificaciones','Follow Up - ISO 27001 - Commercial PPT','control_union_espana_certificaciones_marcomms_iso_27001_commercial_ppt'),
  ('Follow Up - ISO 27001 - Application Form','https://hubs.ly/Q04lzfKX0?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_espana_certificaciones_marcomms_iso_27001_af','contenido','email_mkt','CU Certificaciones','Control Union','España','Certificaciones','Follow Up - ISO 27001 - Application Form','control_union_espana_certificaciones_marcomms_iso_27001_af'),
  ('Follow Up - ISO 27001 - Internal Checklist','https://hubs.ly/Q04lzgMC0?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_espana_certificaciones_marcomms_iso_27001internal_checklist','contenido','email_mkt','CU Certificaciones','Control Union','España','Certificaciones','Follow Up - ISO 27001 - Internal Checklist','control_union_espana_certificaciones_marcomms_iso_27001internal_checklist'),
  ('Cannabis Webinar','https://northamerica.controlunion.com/industry/cannabis/?utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_canada_certificaciones_marcomms_webinar_cannabis','contenido','email_mkt','CU Certificaciones','Control Union','Canada','Certificaciones','Cannabis Webinar','control_union_canada_certificaciones_marcomms_webinar_cannabis'),
  ('ISO 27001 WEBINAR ESPAÑA ICU','https://app.livestorm.co/controlunion/ciberseguridad-en-riesgo-lo-que-no-estas-viendo-y-como-isoiec-270012022-puede-ayudarte?s=2aabf342-06e0-4afa-9dcc-91ed35fa526c&utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_espana_certificaciones_marcomms_icu_iso_27001','contenido','email_mkt','CU Certificaciones','Control Union','España','Certificaciones','ISO 27001 WEBINAR ESPAÑA ICU','control_union_espana_certificaciones_marcomms_icu_iso_27001'),
  ('ISO 27001 WEBINAR ESPAÑA CUSI','https://app.livestorm.co/controlunion/ciberseguridad-en-riesgo-lo-que-no-estas-viendo-y-como-isoiec-270012022-puede-ayudarte?s=2aabf342-06e0-4afa-9dcc-91ed35fa526c&utm_source=contenido&utm_medium=email_mkt&utm_campaign=control_union_espana_certificaciones_marcomms_cusi_iso_27001','contenido','email_mkt','CU Certificaciones','Control Union','España','Certificaciones','ISO 27001 WEBINAR ESPAÑA CUSI','control_union_espana_certificaciones_marcomms_cusi_iso_27001')
) as v(label, url, source, medium, business_unit, organization, country, service, campaign_name, utm_campaign)
where not exists (select 1 from public.utm_links e where e.url = v.url);
